package net

import "net"

var StuMap = map[string]interface{}{
	"IPConn":         net.IPConn{},
	"AddrError":      net.AddrError{},
	"IP":             net.IP{},
	"TCPListener":    net.TCPListener{},
	"UDPAddr":        net.UDPAddr{},
	"IPMask":         net.IPMask{},
	"SRV":            net.SRV{},
	"UnixConn":       net.UnixConn{},
	"Resolver":       net.Resolver{},
	"Buffers":        net.Buffers{},
	"UnixListener":   net.UnixListener{},
	"IPNet":          net.IPNet{},
	"NS":             net.NS{},
	"ParseError":     net.ParseError{},
	"TCPConn":        net.TCPConn{},
	"Dialer":         net.Dialer{},
	"UDPConn":        net.UDPConn{},
	"MX":             net.MX{},
	"IPAddr":         net.IPAddr{},
	"TCPAddr":        net.TCPAddr{},
	"DNSError":       net.DNSError{},
	"DNSConfigError": net.DNSConfigError{},
	"OpError":        net.OpError{},
	"Interface":      net.Interface{},
	"UnixAddr":       net.UnixAddr{},
	"HardwareAddr":   net.HardwareAddr{},
}

var FucMap = map[string]interface{}{
	"ResolveTCPAddr":     net.ResolveTCPAddr,
	"ListenPacket":       net.ListenPacket,
	"ListenIP":           net.ListenIP,
	"DialUDP":            net.DialUDP,
	"InterfaceByIndex":   net.InterfaceByIndex,
	"InterfaceByName":    net.InterfaceByName,
	"FileConn":           net.FileConn,
	"ResolveUDPAddr":     net.ResolveUDPAddr,
	"DialIP":             net.DialIP,
	"ParseCIDR":          net.ParseCIDR,
	"Listen":             net.Listen,
	"CIDRMask":           net.CIDRMask,
	"IPv4Mask":           net.IPv4Mask,
	"ResolveUnixAddr":    net.ResolveUnixAddr,
	"ParseMAC":           net.ParseMAC,
	"InterfaceAddrs":     net.InterfaceAddrs,
	"DialTimeout":        net.DialTimeout,
	"JoinHostPort":       net.JoinHostPort,
	"Interfaces":         net.Interfaces,
	"Pipe":               net.Pipe,
	"ResolveIPAddr":      net.ResolveIPAddr,
	"LookupIP":           net.LookupIP,
	"DialTCP":            net.DialTCP,
	"ListenMulticastUDP": net.ListenMulticastUDP,
	"FileListener":       net.FileListener,
	"ListenUnixgram":     net.ListenUnixgram,
	"DialUnix":           net.DialUnix,
	"ListenUDP":          net.ListenUDP,
	"ListenUnix":         net.ListenUnix,
	"IPv4":               net.IPv4,
	"SplitHostPort":      net.SplitHostPort,
	"ParseIP":            net.ParseIP,
	"FilePacketConn":     net.FilePacketConn,
	"ListenTCP":          net.ListenTCP,
}
